In [3]:
import pandas as pd
df = pd.read_csv("C:\\Users\\Urvi Patel\\health-intelligence-system\\data\\processed\\health_data.csv")

In [4]:
df.shape

(27000, 7)

In [5]:
df.head()

  user_id        date  steps  sleep_hours  heart_rate    stress       spo2
0    U000  2026-01-01   2449     6.015433   83.317026  9.052675  96.083173
1    U000  2026-01-02   2875     3.489037   76.550376  7.588870  96.070815
2    U000  2026-01-03   3079     5.340483   80.155553  6.358311  96.468183
3    U000  2026-01-04   2882     5.722079   74.624164  7.213697  96.965348
4    U000  2026-01-05   4134     5.395254   76.324140  9.869157  94.973280

In [8]:
df.corr(numeric_only=True)

                steps  sleep_hours  heart_rate    stress      spo2
steps        1.000000     0.578748   -0.620594 -0.663767  0.010505
sleep_hours  0.578748     1.000000   -0.470233 -0.512063 -0.003873
heart_rate  -0.620594    -0.470233    1.000000  0.557314 -0.011491
stress      -0.663767    -0.512063    0.557314  1.000000 -0.011892
spo2         0.010505    -0.003873   -0.011491 -0.011892  1.000000

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27000 entries, 0 to 26999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      27000 non-null  str
 1   date         27000 non-null  str
 2   steps        27000 non-null  int64
 3   sleep_hours  27000 non-null  float64
 4   heart_rate   27000 non-null  float64
 5   stress       27000 non-null  float64
 6   spo2         27000 non-null  float64
dtypes: float64(4), int64(1), str(2)
memory usage: 1.8 MB

In [16]:
df["date"] = pd.to_datetime(df["date"])

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 27000 entries, 0 to 26999
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   user_id      27000 non-null  str
 1   date         27000 non-null  datetime64[us]
 2   steps        27000 non-null  int64
 3   sleep_hours  27000 non-null  float64
 4   heart_rate   27000 non-null  float64
 5   stress       27000 non-null  float64
 6   spo2         27000 non-null  float64
dtypes: datetime64[us](1), float64(4), int64(1), str(1)
memory usage: 1.5 MB

In [18]:
df.describe()

,date,steps,sleep_hours,heart_rate,stress,spo2
count,27000,27000.000000,27000.000000,27000.000000,27000.000000,27000.000000
mean,2026-02-14 12:00:00,5689.128852,6.355369,73.642014,5.594237,97.005176
min,2026-01-01 00:00:00,0.000000,3.000000,55.000000,1.000000,93.000000
25%,2026-01-23 00:00:00,3254.750000,5.484455,67.081436,3.872942,96.323460
50%,2026-02-14 12:00:00,5561.000000,6.402159,73.012786,5.475202,96.997965
75%,2026-03-09 00:00:00,7937.250000,7.260452,79.597650,7.260333,97.684811
max,2026-03-31 00:00:00,14649.000000,9.000000,107.177023,10.000000,100.000000
std,NaN,2793.969349,1.239789,8.673087,2.196250,1.006797

In [14]:
df["stress"].value_counts()

stress
10.000000    737
1.000000     146
9.052675       1
7.588870       1
6.358311       1
            ...
4.863187       1
3.625891       1
4.444770       1
5.936951       1
4.328148       1
Name: count, Length: 26119, dtype: int64

In [21]:
import pandas as pd
df = pd.read_csv("C:\\Users\\Urvi Patel\\health-intelligence-system\\data\\processed\\feature_table.csv")
print(df["label"].value_counts())

label
Medium    9978
High      8496
Low       6426
Name: count, dtype: int64